# Generated by Django 6.0.1 on 2026-02-01 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zlauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captchamodel',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
